---
title: '15022021'
author: "Yogesh"
date: "2/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab 3 - **Data visualization**

```{r}
library("tidyverse")
```

```{r}
SPE = read_csv(file = "http://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/ecological/SPE_pitlatrine.csv")
write_csv(x = SPE, file = "data/SPE_pitlatrine.csv")
ENV = read_csv("http://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/ecological/ENV_pitlatrine.csv")
write_csv(x = ENV, file = "data/ENV_pitlatrine.csv")
```
```{r}
write_csv(x = SPE, file = "data/SPE_pitlatrine.csv")
write_csv(x = ENV, file = "data/ENV_pitlatrine.csv")
```


```{r}
SPE %>%
    pivot_longer(cols = -Taxa,
               names_to = "Samples",
               values_to = "OTU_Count") %>%
  full_join(ENV, by = "Samples") %>%
  mutate(site = case_when(str_detect(Samples, "^T") ~ "Tanzania",
                          str_detect(Samples, "^V") ~ "Vietnam")) %>% 
  write_tsv(file = "data/SPE_ENV.tsv")
```

```{r}
SPE_ENV = read_tsv(file = "data/SPE_ENV.tsv")
SPE_ENV
```



```{r -Task1}
ggplot(data = SPE_ENV, 
       mapping = aes(
         x = OTU_Count, 
         y = Taxa,
         fill = site)) +
  geom_boxplot()
```




```{r-Task2}
ggplot(data = SPE_ENV, 
       mapping = aes(
         x = Temp, 
         y = site)) +
  geom_boxplot() +
  coord_flip()
```

```{r - Task3}
ggplot(data = SPE_ENV, 
       mapping = aes(
         x = Temp, 
         y= pH,
         color = site)) +
  geom_point()
```

```{r - Task4}
ggplot(data = SPE_ENV, 
       mapping = aes(
         x = Temp, 
         y= pH,
         color = site,
         label = Samples)) +
  geom_point() +
  geom_label(size = 2)
```

```{r - Task5}
ggplot(data = SPE_ENV, 
       mapping = aes(
         x = NH4, 
         fill = site)) +
geom_density()
```

```{r - Task6}
ggplot(data = SPE_ENV, 
       mapping = aes(x = CODt, 
           y = CODs,
           color = site)) +
  geom_point() +
  geom_smooth(method = lm)
```
```{r - Task7}

ggplot(data = SPE_ENV, 
       mapping = aes(
         x = Taxa,
         y = Samples,
         )) +
  geom_tile(aes(fill = OTU_Count), hjust = 0.5, alpha = 0.4) +
  scale_fill_gradient2(low = ("blue"), mid = "white", high = ("red"), midpoint = 10000) +
  theme_classic(base_size = 7) +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, hjust = 1), aspect.ratio = 1)
```


```{r - newdata}
targets = c("Methanobacteria", "Clostridia", "Actinobacteria",
            "Sphingobacteria", "Anaerolineae")
SPE_ENV_targets = filter(SPE_ENV, Taxa %in% targets)
```


```{r}
library(ggridges)
library(hexbin)
library(viridis)
library(viridisLite)
```


##Task 8 - Plot
```{r}
ggplot(data = SPE_ENV_targets, 
       mapping = aes(
         x = OTU_Count,
         y = Taxa,
         fill = Taxa
       ))+
  geom_density_ridges(alpha = 0.4) +
  facet_wrap(~site)+
  theme_ridges(font_size = 8, font_family = "Avenir", center_axis_labels = TRUE)+
    theme(legend.position = "bottom") +
  labs(y = "Taxa Identified", 
       x = "OTU Count", 
       title = "OTU Count Distribution for 5 Taxa STratified on Site",
       caption = "Data from doi.org/10-1111/1751-7915.12334") +
   theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_viridis_d(
    alpha = 1,
    begin = 0,
    end = 1,
    direction = 1, 
    option = "D",
    aesthetics = "fill"
  )
```


##Task 8 - Plot2
```{r}
ggplot(data = SPE_ENV_targets, 
       mapping = aes(
         x = OTU_Count,
         y = Taxa,
         fill = Taxa
       ))+
  geom_density_ridges(alpha = 0.4) +
  facet_wrap(~site)+
  theme_minimal(base_family = "Avenir", base_size = 10)+
    theme(legend.position = "bottom", plot.title = element_text(hjust = 0.5, size = 14)) +
  labs(y = "Taxa Identified", 
       x = "OTU Count", 
       title = "OTU Count Distribution for 5 Taxa STratified on Site",
       caption = "Data from doi.org/10-1111/1751-7915.12334") +
  scale_fill_viridis_d(
    alpha = 1,
    begin = 0,
    end = 1,
    direction = 1, 
    option = "D",
    aesthetics = "fill"
  )
```

# Task 9: Group assignment

x = 
y =

```{r - newdata}
targets = c("Actinobacteria")
SPE_ENV_Actinobac = filter(SPE_ENV, Taxa %in% targets)
```

```{r}
ggplot(data = SPE_ENV_targets,
       mapping = aes(
         y = OTU_Count,
         x = Temp,
         color = Taxa
       ))+
  facet_wrap(~site)+
  geom_point(
    mapping = aes(fill = Taxa),
    shape = 21, color = "black")+
  geom_smooth(se = FALSE) +
  theme_classic() +
  scale_y_log10()
```


```{r}
ggplot(data = SPE_ENV_targets,
       mapping = aes(
         y = OTU_Count,
         x = Temp,
         color = site
       ))+
  facet_wrap(~Taxa)+
  geom_point(
    mapping = aes(fill = site),
    shape = 21, color = "black")+
  geom_smooth(se = FALSE) +
  theme_classic() +
  scale_y_log10()
```

```{r message=FALSE, warning=FALSE}
targets = c("Clostridia", "Actinobacteria",
            "Sphingobacteria", "Anaerolineae")
SPE_ENV_targets = filter(SPE_ENV, Taxa %in% targets)

ggplot(data = SPE_ENV_targets,
       mapping = aes(
         x = Temp,
         y = OTU_Count,
         color = site)
       )+
  geom_smooth(se=FALSE)+
  facet_wrap(~Taxa)+
  geom_point(shape = 21, size = 0.5)+
  scale_y_log10()+
  theme_minimal( base_family = "Arial", base_size = 8) +
  theme(aspect.ratio = 1, legend.position = "bottom", 
        panel.spacing = unit(1, "lines"))+
  labs( x = "Temperature",
        y = "OTU Count",
        title = "Relation between OTU count and temperature",
        subtitle = "Group assignment - Lab3- Group 4",
        color = "")
```








# Cancer data playing around
```{r}

library("tidyverse")
library("datamicroarray")
data('gravier', package = 'datamicroarray')
set.seed(676571)
cancer_data=mutate(as_tibble(pluck(gravier,"x")),y=pluck(gravier,"y"),pt_id=1:length(pluck(gravier, "y")),age=round(rnorm(length(pluck(gravier,"y")),mean=55,sd=10),1))
cancer_data=rename(cancer_data,event_label=y)
cancer_data$age_group=cut(cancer_data$age,breaks=seq(10,100,by=10))
select(slice(cancer_data,1:8),pt_id,age,age_group,event_label,1:5)

plt1 <- ggplot(data = cancer_data, 
       mapping = aes(
         x = age_group,
         y = g1C01,
         color = event_label
         )) +
  geom_tile(hjust = 0.5, alpha = 0.4) +
  scale_fill_gradient2(low = ("blue"), mid = "white", high = ("red"), midpoint = 10000) +
  theme_classic(base_size = 7) +
  geom_boxplot(alpha = 0.2)+
  theme(legend.position = "bottom")

plt2 <-ggplot(data = cancer_data, 
       mapping = aes(
         x = age_group,
         y = g3F05,
         color = event_label
         )) +
  geom_tile(hjust = 0.5, alpha = 0.4) +
  scale_fill_gradient2(low = ("blue"), mid = "white", high = ("red"), midpoint = 10000) +
  theme_classic(base_size = 7) +
  geom_boxplot(alpha = 0.2)+
  theme(legend.position = "bottom")
```
```{r}
plt1 + plt2
```





