---
title: "Untitled"
author: "Yogesh"
date: "3/8/2021"
output: html_document
---

```{r, eval=FALSE, echo=FALSE}
library(tidyverse)
library(broom)
library(patchwork)
library(knitr)
```

```{r}
load(file = "data/gravier.RData") 
gravier_data <- 
mutate(as_tibble(pluck(gravier, "x")),
       outcome = pluck(gravier, "y"))

gravier_data <- 
  gravier_data %>% 
  select("outcome", everything())

gravier_data <- 
  gravier_data %>% 
  mutate(outcome = 
    case_when(outcome == "good" ~ 0,
              outcome == "poor" ~ 1)
  )
```


```{r}
gravier_data_wide = gravier_data %>%
  select(outcome, pull(gravier_data_nested, gene))
```

##PCA plot

```{r}
pca_fit <- gravier_data_wide %>% 
  select(where(is.numeric)) %>% 
  prcomp(scale = TRUE)

```

```{r}
pca_fit %>%
  augment(gravier_data_wide) %>% 
  mutate(outcome = factor(outcome)) %>% 
  ggplot(mapping = aes(x = .fittedPC1,
                       y = .fittedPC2,
                       color = outcome))+
  geom_point(size = 1.5) +
  theme_classic()+
  theme(legend.position = "bottom")
```

##Rotation plot

```{r}
pca_fit %>%
  tidy(matrix = "rotation")
```

```{r}
# define arrow style for plotting
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit %>%
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  coord_fixed() + # fix aspect ratio to 1:1
  theme_minimal()
```

## Variance explained by each PC

```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit %>%
  tidy(matrix = "eigenvalues") %>%
  slice_max(percent, n=10) %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 1) +
  scale_x_continuous(breaks = 1:10) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal()
```





